### ISSUE TITLE
Inconsistency between `Ldot` and `L periodcentered.loclCAT.case`

### ISSUE THREAD

**Issue by eliheuer** [SorkinType/Danfo#19]
This issue is based on a comment in the Agbalumo: Version 1.000 PR: https://github.com/google/fonts/pull/6830#issuecomment-1754572801

There is an inconsistency between `Ldot` and `L periodcentered.loclCAT.case`;

since the `locl` feature is making the substitution with `periodcentered.loclCAT`, `Ldot` is a bit useless here, it can be kept for backward compatibility or removed.
`L periodcentered.loclCAT.case  L` doesn't display the dot in the middle of the 2 L.
A good practice would be to achieve that through with sidebearing of `periodcentered.loclCAT.case`, then if `Ldot` is meant to stay, it can be a component of `L periodcentered.loclCAT.case` with automatic alignment to make sure both strings are consistent.

<img width="79" alt="273810332-5a455bb0-66f3-4d0b-aafb-6d44d0d56d74" src="https://github.com/SorkinType/Agbalumo/assets/5162664/1eca5ce3-703c-4f5e-a40d-e4d14f847dec">

**Comment by EbenSorkin** [comment]
resolved
