### ISSUE TITLE
Vertical Metrics issue in Penpot?

### ISSUE THREAD

**Issue by eliheuer** [SorkinType/Danfo#20]
[Penpot](https://penpot.app/) gives this error when using Agbalumo:
![unnamed](https://github.com/SorkinType/Agbalumo/assets/5162664/b6c275fb-0285-4bfe-9a1c-13f3335fa4ff)

**Comment by davelab6** [comment]
This was a penpot bug, right?

**Comment by eliheuer** [comment]
This is an upstream issue with PenPot, not with this font or Google Fonts QA: https://github.com/penpot/penpot/blob/02399add7a49b24aec28bb7d09c8d7371577ef76/frontend/src/app/main/data/fonts.cljs#L111-L115
