### ISSUE TITLE
Do we need shaper glot to work?

### ISSUE THREAD

**Issue by EbenSorkin** [SorkinType/Danfo#9]
Failed with ModuleNotFoundError: No module named                      
          'shaperglot'

**Comment by eliheuer** [comment]
Issues like this should go in the Font Bakery issue tracker

**Comment by eliheuer** [comment]
I made an issue here: https://github.com/fonttools/fontbakery/discussions/4291

**Comment by felipesanches** [comment]
here's the fix: https://github.com/SorkinType/Agbalumo/pull/14

**Comment by eliheuer** [comment]
Thanks @felipesanches! Should we update the GFPT to do this by default? 
https://github.com/googlefonts/googlefonts-project-template/blob/main/requirements.txt

**Comment by felipesanches** [comment]
yes, please

**Comment by felipesanches** [comment]
you can close this issue now that the problem is fixed
